print("REGISTRO DE CLIENTES:")
print("-----------------------")
print("Ingrese DNI:")
dni = input()
print("Ingrese primer nombre:")
nombre = input()
print("Ingrese primer apellido")
apellido = input()
print("Ingresa la edad")
edad = input()